### ISSUE TITLE
What should backward function return?

### ISSUE THREAD

**Issue by Ze-Yang** [ag14774/diffdist#3]
Hi, I am a beginer to write custom backward function. I indeed understand the gradient calculation procedure of function `AllGatherFunc`, but I am confuse about why the backward func should return in the form as below. What's the `None` means, and why should add the `grads` back? Isn't `grad_out` the final result? Thanks.
https://github.com/ag14774/diffdist/blob/b5c17c7354bbbe98b6e8a791ea78614861b4997a/diffdist/functions.py#L133

**Comment by ag14774** [comment]
Sorry for the late reply. The input of the `backward` function is a gradient with respect to the output of the `forward`. So let's say you use the output of the `forward` function and you do some calculations on it and compute a loss. Backward will give you the gradient of the loss with respect to the output of the `forward`. What you need to do in the `backward` is to further 'push' this gradient up. So we need the gradient of the loss with respect to each one of the inputs of the forward. So in your example `grad_out` is the gradient with respect to the input `tensor`. Then we follow by 2 `None`s which is the gradient of the loss with respect to `group` and `inplace` (which is of course not defined since those are just function arguments and not mathematical variables!). Then because `gather_list` was also an input, we need to also return the gradients with respect to that. Since `gather_list` was also the output, the gradients `grads` remains unchanged and we just return it as is. Therefore we need one gradient for each input of `forward`

**Comment by Ze-Yang** [comment]
Thanks for your kind help.
